{
  lib,
  stdenv,
  pkgs,
  fetchFromGitHub,
  baseURL ? "http://localhost",
}:

let
  re-terminal-theme = builtins.fetchTarball {
    # why do i need this if it's in the github for the website?
    name = "hugo-theme-re-terminal";
    url = "https://github.com/mirus-ua/hugo-theme-re-terminal/archive/refs/tags/v2.3.4.tar.gz";
    sha256 = "sha256-7dG2miZ0VaUaJMseghJB+6kSb8j/dbRZT3GuMnK6vEk="; # version v2.3.4
  };
in
stdenv.mkDerivation rec {
  pname = "hugo-site";
  version = "0.2";

  src = fetchFromGitHub {
    owner = "TheCarton";
    repo = "luke-vandermale-site";
    rev = "edb87f5dd9096f35f39e888690db2f2fafab8e30";
    # tag = "v0.0.2-alpha";

    # This fetches the zip generated by github at the specified tag.
    # rev corresponds to the Git commit hash or tag (e.g v1.0) that will be downloaded from Git.

    # SHA256 hash is required for reproducibility. When you try to build
    # the package the hash will cause a failure. You can then copy the correct
    # hash here and build the package again.
    hash = "sha256-/nSXQKtr8uOk+d9dQgegmNTV3imbUTIAeBdmr5JiaM4=";
    # hash corresponds to the hash of the extracted directory.
  };

  # How to update the website:
  # Push new updates to the luke-vandermale-site repo.
  # Get either the tag or the Git commit hash of the new version tag goes in tag, Git commit hash in rev.
  # Replace the above hash with an empty string.
  # Rebuild the server (alias rebuild or nixos-rebuild switch)
  # Copy the new hash from the resuling error message into the hash paramater above.
  # Rebuild again.

  nativeBuildInputs = [ pkgs.hugo ];

  installPhase = ''
    mkdir -p themes/re-terminal;
    cp -r ${re-terminal-theme}/* themes/re-terminal/;
    hugo -b ${baseURL} -t re-terminal -d $out;
  '';

  meta = {
    description = "Hugo project for ${pname}";
    homepage = "https://www.test-site.com";
  };
}
