{
  lib,
  stdenv,
  pkgs,
  fetchFromGitHub,
  baseURL ? "http://localhost",
}:

let
  hugoTheme = builtins.fetchTarball {
    # why do i need this if it's in the github for the website?
    name = "hugo-theme-ananke";
    url = "https://github.com/theNewDynamic/gohugo-theme-ananke/archive/refs/tags/v2.12.0.tar.gz";
    # This was updated from the tutorial as the previous theme is deprecated.
    sha256 = "sha256:1y356jq70fiaq52shhcmam499rfmc35yxb3x1f37qj8z8qhlp33l";
  };
in
stdenv.mkDerivation rec {
  pname = "hugo-site";
  version = "0.2";

  src = fetchFromGitHub {
    owner = "TheCarton";
    repo = "luke-vandermale-site";
    rev = "ccb766ff51b2182993cef4e356f3f52371653324";

    # tag = "v0.0.1-alpha";
    # This fetches the zip generated by github at the specified tag.
    # rev corresponds to the Git commit hash or tag (e.g v1.0) that will be downloaded from Git.

    # SHA256 hash is required for reproducibility. When you try to build
    # the package the hash will cause a failure. You can then copy the correct
    # hash here and build the package again.
    hash = "sha256-FCVEuoY6SuVrAjol5gSIfPuZR9CtAUfBU0YLibWy4kY=";
    # this is the only one that affects the build
  };

  nativeBuildInputs = [ pkgs.hugo ];

  installPhase = ''
    mkdir -p themes/ananke;
    cp -r ${hugoTheme}/* themes/ananke/;
    hugo -b ${baseURL} -t ananke -d $out;
  '';

  meta = {
    description = "Hugo project for ${pname}";
    homepage = "https://www.test-site.com";
  };
}
